version: '3.8'

services:
  app:
    build: .
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: root
      MYSQL_PASSWORD:
    volumes:
      - ./data:/var/lib/mysql

  # Add Node.js service for Vue.js build process
  node:
    image: node:14
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    command: npm run build
