version: "3.9"  # Remove this line or update to '3.9'

services:
  app:
    build: .
    ports:
      - "8080:80"  # Change this line to map to a different port
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: laravel
      MYSQL_USER: root
      MYSQL_PASSWORD:
    volumes:
      - ./data:/var/lib/mysql

  # Add Node.js service for Vue.js build process
  node:
    image: node:14
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    command: npm run build
